# Coursera_Capstone
## This Notebook Will Be Mainly Used For Couresra_Capstone Project (IBM PROFESSIONAL)

### IMPORT PANDAS,NUMPY,RESAMPLE (FOR DOWNSAMPLING)



In [8]:
import pandas as pd
import numpy as np
from sklearn.utils import resample
from sklearn import preprocessing
print('Hello Capstone Project Course!')

Hello Capstone Project Course!


### DOWNLOADING DATASET (Data-Collisions.csv)

In [9]:
!wget -O Data-Collisions.csv https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv

--2020-09-06 04:24:00--  https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv
Resolving s3.us.cloud-object-storage.appdomain.cloud (s3.us.cloud-object-storage.appdomain.cloud)... 67.228.254.196
Connecting to s3.us.cloud-object-storage.appdomain.cloud (s3.us.cloud-object-storage.appdomain.cloud)|67.228.254.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 73917638 (70M) [text/csv]
Saving to: ‘Data-Collisions.csv’

100%[======================================>] 73,917,638  34.8MB/s   in 2.0s   

2020-09-06 04:24:03 (34.8 MB/s) - ‘Data-Collisions.csv’ saved [73917638/73917638]



### READING DOWNLOADED CSV FILE

In [10]:
df=pd.read_csv('Data-Collisions.csv')
df.columns.values


/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


array(['SEVERITYCODE', 'X', 'Y', 'OBJECTID', 'INCKEY', 'COLDETKEY',
       'REPORTNO', 'STATUS', 'ADDRTYPE', 'INTKEY', 'LOCATION',
       'EXCEPTRSNCODE', 'EXCEPTRSNDESC', 'SEVERITYCODE.1', 'SEVERITYDESC',
       'COLLISIONTYPE', 'PERSONCOUNT', 'PEDCOUNT', 'PEDCYLCOUNT',
       'VEHCOUNT', 'INCDATE', 'INCDTTM', 'JUNCTIONTYPE', 'SDOT_COLCODE',
       'SDOT_COLDESC', 'INATTENTIONIND', 'UNDERINFL', 'WEATHER',
       'ROADCOND', 'LIGHTCOND', 'PEDROWNOTGRNT', 'SDOTCOLNUM', 'SPEEDING',
       'ST_COLCODE', 'ST_COLDESC', 'SEGLANEKEY', 'CROSSWALKKEY',
       'HITPARKEDCAR'], dtype=object)

### CREATING DATAFRAME WITH ONLY REQUIRED COLUMNS

In [11]:
df_required=df[['SEVERITYCODE','WEATHER','ROADCOND','LIGHTCOND']]
df_required.head()

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND
0             2  Overcast      Wet                 Daylight
1             1   Raining      Wet  Dark - Street Lights On
2             1  Overcast      Dry                 Daylight
3             1     Clear      Dry                 Daylight
4             2   Raining      Wet                 Daylight

In [12]:
df_required.shape

(194673, 4)

In [13]:
df_required.dtypes

SEVERITYCODE     int64
WEATHER         object
ROADCOND        object
LIGHTCOND       object
dtype: object

### TOTAL NAN VALUES PER EACH COLUMN

In [14]:
df_required.isnull().sum()

SEVERITYCODE       0
WEATHER         5081
ROADCOND        5012
LIGHTCOND       5170
dtype: int64

### CATEGORY NAME AND FREQUENCY IN SEVERITYCODE ATTRIBUTE

In [15]:
df_required['SEVERITYCODE'].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

### CATEGORY NAME AND FREQUENCY IN WEATHER ATTRIBUTE

In [16]:
df_required['WEATHER'].value_counts()

Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

### CATEGORY NAME AND FREQUENCY IN ROADCOND ATTRIBUTE

In [17]:
df_required['ROADCOND'].value_counts()

Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

### CATEGORY NAME AND FREQUENCY IN LIGHTCOND ATTRIBUTE

In [18]:
df_required['LIGHTCOND'].value_counts()

Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

### CALCULATING MODE OF WEATHER ATTRIBUTE

In [19]:
weathermode=df_required['WEATHER'].mode()
weathermode

0    Clear
dtype: object

### REPLCING MISSING WEATHER ATTRIBUTE VALUES WITH MODE OF WEATHER ATTRIBUTE

In [20]:
df_required['WEATHER'].replace(np.nan, 'Clear', inplace=True)

/opt/conda/envs/Python36/lib/python3.6/site-packages/pandas/core/generic.py:6586: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


### CALCULATING MODE OF ROADCOND ATTRIBUTE

In [21]:
roadcondmode=df_required['ROADCOND'].mode()
roadcondmode

0    Dry
dtype: object

### REPLCING MISSING ROADCOND ATTRIBUTE VALUES WITH MODE OF ROADCOND ATTRIBUTE

In [22]:
df_required['ROADCOND'].replace(np.nan, 'Dry', inplace=True)

### CALCULATING MODE OF LIGHTCOND ATTRIBUTE

In [23]:
lightcondmode=df_required['LIGHTCOND'].mode()
lightcondmode

0    Daylight
dtype: object

### REPLCING MISSING LIGHTCOND ATTRIBUTE VALUES WITH MODE OF LIGHTCOND ATTRIBUTE

In [24]:
df_required['LIGHTCOND'].replace(np.nan, 'Daylight', inplace=True)

### CONVERTING OBJECT TYPE ATTRIBUTES TO CATEGORY TYPE USING 

In [25]:
df_required['WEATHER'] = df_required['WEATHER'].astype('category')
df_required['ROADCOND'] = df_required['ROADCOND'].astype('category')
df_required['LIGHTCOND'] = df_required['LIGHTCOND'].astype('category')


/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See t

### OBJECT DATATYPES CONVERTED TO CATEGORY DATATYPE

In [26]:
df_required.dtypes

SEVERITYCODE       int64
WEATHER         category
ROADCOND        category
LIGHTCOND       category
dtype: object

### LABEL ENCODING CATEGORY ATTRIBUTES

In [27]:
df_required["WEATHER_CAT"] = df_required["WEATHER"].cat.codes
df_required["ROADCOND_CAT"] = df_required["ROADCOND"].cat.codes
df_required["LIGHTCOND_CAT"] = df_required["LIGHTCOND"].cat.codes

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See t

In [28]:
df_required.head()

SEVERITYCODE   WEATHER ROADCOND                LIGHTCOND  WEATHER_CAT  \
0             2  Overcast      Wet                 Daylight            4   
1             1   Raining      Wet  Dark - Street Lights On            6   
2             1  Overcast      Dry                 Daylight            4   
3             1     Clear      Dry                 Daylight            1   
4             2   Raining      Wet                 Daylight            6   

   ROADCOND_CAT  LIGHTCOND_CAT  
0             8              5  
1             8              2  
2             0              5  
3             0              5  
4             8              5

### DOWNSAMPLING SEVERITYCODE FOR ACCURATE ALGORITHM

In [29]:
df_requiredmajority = df_required[df_required.SEVERITYCODE==1]
df_requiredminority = df_required[df_required.SEVERITYCODE==2]

df_requiredmajority_downsampled = resample(df_requiredmajority, 
                                           replace=False,    
                                           n_samples=58188,     
                                           random_state=123) 

df_requireddownsampled = pd.concat([df_requiredmajority_downsampled, df_requiredminority])
df_requireddownsampled.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [30]:
df_requireddownsampled.shape

(116376, 7)

In [31]:
df_requireddownsampled.isnull().sum()

SEVERITYCODE     0
WEATHER          0
ROADCOND         0
LIGHTCOND        0
WEATHER_CAT      0
ROADCOND_CAT     0
LIGHTCOND_CAT    0
dtype: int64

In [32]:
df_requireddownsampled.dtypes

SEVERITYCODE        int64
WEATHER          category
ROADCOND         category
LIGHTCOND        category
WEATHER_CAT          int8
ROADCOND_CAT         int8
LIGHTCOND_CAT        int8
dtype: object

# METHODOLOGY

<ol>
<li>K-Nearest Neighbor (KNN)</li>
     KNN will help us predict the severity code by finding the most similar to data point within given k distance.
<li>Decision Tree</li>
    A decision tree model gives us a layout of all possible outcomes so we can fully analyze the concequences of a decision. It context, the decision tree observes all possible outcomes of different weather conditions.
    
<li>Logistic Regression</li>
    Because our dataset only provides us with two severity code outcomes, our model will only predict one of those two classes. This makes our data binary, which is perfect to use with logistic regression.
</ol>


## X and y

In [33]:
X=np.asarray(df_requireddownsampled[['WEATHER_CAT','ROADCOND_CAT','LIGHTCOND_CAT']])
X[0:5]

array([[ 6,  8,  2],
       [ 1,  0,  5],
       [10,  7,  8],
       [ 1,  0,  5],
       [ 1,  0,  5]], dtype=int8)

In [34]:
y=np.asarray(df_requireddownsampled['SEVERITYCODE'])
y[0:5]



array([1, 1, 1, 1, 1])

## NORMALIZE DATASET

In [35]:
X=preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int8 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 1.15634067,  1.52957631, -1.45245862],
       [-0.70578591, -0.68099493,  0.39105021],
       [ 2.64604194,  1.25325491,  2.23455904],
       [-0.70578591, -0.68099493,  0.39105021],
       [-0.70578591, -0.68099493,  0.39105021]])

## TRAIN AND TEST SPLIT

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size=0.3, random_state=1)
print('Train set:', X_train.shape , y_train.shape)
print('Test set:', X_test.shape , y_test.shape)

Train set: (81463, 3) (81463,)
Test set: (34913, 3) (34913,)


In [37]:
from sklearn.metrics import jaccard_similarity_score



# MODELING

## K-NEAREST NEIGHBORS

In [43]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
Ksjacard = 30
jacard_acc = np.zeros((Ksjacard-1))
for n in range(1,Ksjacard):
    
    #Train Model and Predict  
    neigh = KNeighborsClassifier(n_neighbors = n).fit(X_train,y_train)
    yhat=neigh.predict(X_test)
    jacard_acc[n-1] = jaccard_similarity_score(y_test, yhat)

jacard_acc

array([0.50110274, 0.50018618, 0.50620113, 0.50580013, 0.50654484,
       0.50488357, 0.50370922, 0.50425343, 0.50892218, 0.50774783,
       0.52189729, 0.51794461, 0.51783003, 0.51777275, 0.51768682,
       0.50754733, 0.51757225, 0.51891845, 0.51831696, 0.50975281,
       0.5189471 , 0.50946639, 0.51837424, 0.50511271, 0.5185461 ,
       0.51118495, 0.52092344, 0.52086615, 0.52175407])

## Printing Best 'K'

In [44]:
print( "The best accuracy was with", jacard_acc.max(), "with k=", jacard_acc.argmax()+1) 

The best accuracy was with 0.521897287543322 with k= 11


## DECISION TREE

In [45]:
from sklearn.tree import DecisionTreeClassifier

decisionjacard = 35
decisionjacard_acc = np.zeros((decisionjacard-1))
for n in range(1,decisionjacard):
    
    #Train Model and Predict  
    decisionTree = DecisionTreeClassifier(criterion="entropy", max_depth = n).fit(X_train,y_train)
    decisionTreehat=decisionTree.predict(X_test)
    decisionjacard_acc[n-1] = jaccard_similarity_score(y_test, decisionTreehat)

    
decisionjacard_acc

array([0.54203305, 0.54850629, 0.54850629, 0.55432074, 0.55518002,
       0.5573855 , 0.55755736, 0.55755736, 0.55566694, 0.55549509,
       0.55532323, 0.55535187, 0.55540916, 0.55532323, 0.55520866,
       0.55520866, 0.55520866, 0.55520866, 0.55520866, 0.55520866,
       0.55520866, 0.55520866, 0.55520866, 0.55520866, 0.55520866,
       0.55520866, 0.55520866, 0.55520866, 0.55520866, 0.55520866,
       0.55520866, 0.55520866, 0.55520866, 0.55520866])

## PRINTING BEST 'MAXDEPTH'

In [46]:
print( "The best accuracy was with", decisionjacard_acc.max(), "with max_depth=", decisionjacard_acc.argmax()+1) 

The best accuracy was with 0.5575573568584767 with max_depth= 7


## LOGISTIC REGRESSION

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
logisticjacard = 25
logisticjacard_acc = np.zeros((logisticjacard-1))
for n in range(1,logisticjacard):
    
    #Train Model and Predict  
    LR = LogisticRegression(C=n, solver='liblinear').fit(X_train,y_train)
    lrhat=LR.predict(X_test)
    logisticjacard_acc[n-1] = jaccard_similarity_score(y_test, lrhat)

    
logisticjacard_acc


array([0.53169307, 0.53169307, 0.53169307, 0.53169307, 0.53169307,
       0.53169307, 0.53169307, 0.53169307, 0.53169307, 0.53169307,
       0.53169307, 0.53169307, 0.53169307, 0.53169307, 0.53169307,
       0.53169307, 0.53169307, 0.53169307, 0.53169307, 0.53169307,
       0.53169307, 0.53169307, 0.53169307, 0.53169307])

In [49]:
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

## PRINTING BEST HYPER PARAMETER

In [50]:
print( "The best accuracy was with", logisticjacard_acc.max(), "with C=", logisticjacard_acc.argmax()+1) 

The best accuracy was with 0.5316930656202561 with C= 1


# RESULTS & EVALUATION 

### K-NEAREST NEIGHBOR JACARD INDEX

#### MODEL IS ACCURATE WITH K=11

In [51]:
neigh1 = KNeighborsClassifier(n_neighbors = 11).fit(X_train,y_train)
yhat1=neigh1.predict(X_test)

In [52]:
jaccard_similarity_score(y_test, yhat1)

0.521897287543322

### K-NEAREST NEIGHBOR F1-SCORE

In [53]:
f1_score(y_test,yhat1, average='weighted')

0.520638364931839

### DECISION TREE JACARD INDEX

##### MODEL IS ACCURATE WITH MAX_DEPTH=7

In [54]:
decisionTree1 = DecisionTreeClassifier(criterion="entropy", max_depth = 7).fit(X_train,y_train)
decisionTreehat1= decisionTree1.predict(X_test)
jaccard_similarity_score(y_test, decisionTreehat1)

0.5575573568584767

### DECISION TREE F1-SCORE

In [55]:
f1_score(y_test, decisionTreehat1, average='weighted')

0.5324948342068622

### LOGISTIC REGRESSION JACARD INDEX

In [56]:
LR1 = LogisticRegression(C=1, solver='liblinear').fit(X_train,y_train)
lrhat1=LR1.predict(X_test)
jaccard_similarity_score(y_test, lrhat1)

0.5316930656202561

### LOGISTIC REGRESSION F1-SCORE

In [57]:
f1_score(y_test, lrhat1, average='weighted')

0.5176680676444921

### LOGISTIC REGRESSION LOG LOSS 

In [58]:
from sklearn.metrics import log_loss

In [59]:
yhat_prob=LR1.predict_proba(X_test)
log_loss(y_test,yhat_prob)

0.6829193712785075

## DISCUSSION

In the beginning of this notebook, we had categorical data that was of type 'object'. This is not a data type that we could have fed through an algoritim, so label encoding was used to create new attributes that were of type int8; a numerical data type.

After solving that issue we were presented with another - imbalanced data. As mentioned earlier, class 1 was nearly three times larger than class 2. The solution to this was downsampling the majority class with sklearn's resample tool. We downsampled to match the minority class exactly with 58188 values each.

Once we analyzed and cleaned the data, it was then fed through three ML models; K-Nearest Neighbor, Decision Tree and Logistic Regression. Although the first two are ideal for this project, logistic regression made most sense because of its binary nature.

Evaluation metrics used to test the accuracy of our models were jaccard index, f-1 score and logloss for logistic regression. Choosing different k, max depth and hyparameter C values helped to improve our accuracy to be the best possible.



## CONCLUSION

Based on historical data conditions pointing to certain classes, we can conclude that particular conditions have a somewhat impact on whether or not travel could result in property damage (class 1) or injury (class 2).

Thank you !!